"""
Portfolio action domain model.

MF-347.1

Represents investor operational tasks generated
from portfolio intelligence.
"""

from dataclasses import dataclass


@dataclass(slots=True)
class PortfolioAction:
    """
    Operational action generated by MeridianForge.
    """

    action_type: str

    description: str

    priority: str

    status: str = "OPEN"

    asset_id: str | None = None

    def complete(self) -> None:
        """
        Mark action as completed.
        """

        self.status = "COMPLETED"

    @property
    def is_open(self) -> bool:
        """
        Return whether action requires attention.
        """

        return self.status == "OPEN"
